version: '3.8'

services:
  # 微服务应用
  microservice-ds:
#    image: microservice-ds:1.0
    build:
      context: ./microservice-ds
      dockerfile: Dockerfile
    container_name: microservice-ds
    ports:
      - "${BACKEND_PORT}:9091"
    volumes:
      - ./config/java:/app/config
      - ./log:/app/log
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
      - BACKEND_PORT=${BACKEND_PORT}
      - DIFY_URL=${DIFY_URL}
    restart: unless-stopped
    networks:
      - microservice-network

  # Nginx服务
  nginx:
    image: nginx:alpine
    container_name: microservice-nginx
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - ./update-config.sh:/tmp/update-config.sh:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/demo:/usr/share/nginx/html
      - ./log/nginx:/var/log/nginx
      - ./.env:/app/.env
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP:-192.168.11.205}
    command: >
      /bin/sh -c "
        sleep 2;  # 等待文件系统挂载完成
        cp /tmp/update-config.sh /docker-entrypoint.d/update-config.sh;
        chmod +x /docker-entrypoint.d/update-config.sh;
        /bin/sh /docker-entrypoint.d/update-config.sh;
        nginx -g 'daemon off;'
      "
    depends_on:
      - microservice-ds
    restart: unless-stopped
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge 