llm:
  provider: dify

dify:
  api:
    base-url: http://192.168.11.205
    chat-agent-token: Bearer app-Ug8kHQck7eFWEQ9I3WFcNk7J

rag-flow:
  api:
    base-url: http://192.9.100.162
    api-key: Bearer ragflow-I2OTNiZjQyZmZiODExZWY5MDIyMDI0Mm
