version: '3'

services:
  postgres:
    image: postgres:12
    container_name: diit-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - diit-network
    restart: always

  operation-backend:
    build:
      context: ./system-server
      dockerfile: Dockerfile
    # image: operation-docker-backend:latest
    container_name: diit-operation-backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - CONTEXT_PATH=${BACKEND_CONTEXT_PATH}
    ports:
      - "${BACKEND_PORT}:32003"
    depends_on:
      - postgres
    networks:
      - diit-network
    restart: always

  operation-frontend:
    build:
      context: ./nginx
      dockerfile: Dockerfile
#    image: operation-docker-frontend:latest
    container_name: diit-operation-frontend
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend
    networks:
      - diit-network
    restart: always

networks:
  diit-network:
    driver: bridge 