server:
  port: 9092
  tomcat:
    connection-timeout: 5000000
    max-swallow-size: 100MB

spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      enabled: true