spring:
  datasource:
    dynamic:
      primary: primary # 设置默认的数据源
      strict: false # 严格匹配数据源，默认false. true未匹配到指定数据源时抛异常，false使用默认数据源
      datasource:
        primary:
          url: jdbc:postgresql://192.9.100.162:5433/houtu
          username: postgres
          password: postgres
          driver-class-name: org.postgresql.Driver
        dify:
          url: jdbc:postgresql://192.168.11.205:5432/dify
          username: postgres
          password: difyai123456
          driver-class-name: org.postgresql.Driver
        ragflow:
          url: jdbc:mysql://192.9.100.11:5455/rag_flow
          username: root
          password: infini_rag_flow
          driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 60000
      max-lifetime: 1800000
      pool-name: HikariCP
      connection-test-query: SELECT 1