# 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    org.mybatis: debug
    org.mybatis.spring: warn
    org.apache.ibatis: debug
    org.apache.ibatis.logging.jdbc.BaseJdbcLogger: warn
    com.diit.ds.mapper: debug
