spring:
  web:
    resources:
      static-locations: classpath:/static/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/,file:preview/
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# 自定义静态资源目录配置
file:
  preview-path: preview/
  preview-mapping: /preview/